framework:
    messenger:
        serializer:
                format: 'jsonld'

        transports:
            kitchen: '%env(MESSENGER_TRANSPORT_KITCHEN)%'
            delivery_truck: '%env(MESSENGER_TRANSPORT_DELIVERY_TRUCK)%'

        routing:
            'App\Message\PrepareOrderMessage': kitchen
            'App\Message\DeliverOrderMessage': delivery_truck
