framework:
    messenger:
        serializer:
                format: 'jsonld'

        transports:
            prepare: '%env(MESSENGER_TRANSPORT_PREPARE)%'
            deliver: '%env(MESSENGER_TRANSPORT_DELIVER)%'

        routing:
            'App\Message\PrepareOrderMessage': prepare
            'App\Message\DeliverOrderMessage': deliver
